using App.Models;

namespace App.Services
{
    public class PlanetService : List<Planet>
    {
        List<Planet> listPlanet = new List<Planet>()
        {
            new Planet(1, "Sun", "The Sun is the Solar System's star and by far its most massive component. Its large mass (332,900 Earth masses),[64] which comprises 99.86% of all the mass in the Solar System,[65] produces temperatures and densities in its core high enough to sustain nuclear fusion of hydrogen into helium.[66] This releases an enormous amount of energy, mostly radiated into space as electromagnetic radiation peaking in visible light.[67][68]"),
            new Planet(2, "Mercury", "Mercury (0.307–0.588 AU (45.9–88.0 million km; 28.5–54.7 million mi) from the Sun[89]) is the closest planet to the Sun. The smallest planet in the Solar System (0.055 MEarth), Mercury has no natural satellites. The dominant geological features are impact craters or basins with ejecta blankets, the remains of early volcanic activity including magma flows, and lobed ridges or rupes that were probably produced by a period of contraction early in the planet's history.[90] Mercury's very tenuous atmosphere consists of solar-wind particles trapped by Mercury's magnetic field, as well as atoms blasted off its surface by the solar wind.[91][92] Its relatively large iron core and thin mantle have not yet been adequately explained. Hypotheses include that its outer layers were stripped off by a giant impact, or that it was prevented from fully accreting by the young Sun's energy.[93][94] There have been searches for Vulcanoids, asteroids in stable orbits between Mercury and the Sun, but none have been discovered.[9"),
            new Planet(3, "Venus", "Venus is the second planet from the Sun. It is a rocky planet with the thickest atmosphere of all the rocky bodies in the Solar System, and the only one with a mass and size that is close to that of its orbital neighbour Earth. Orbiting inferiorly (inside of Earth's orbit), it appears in Earth's sky always close to the Sun, as either a morning star or evening star. While this is also true for Mercury, Venus appears as such much more prominently, since it is the third brightest object in Earth's sky, after the Moon and the Sun,[20][21] appearing brighter than any other star-like classical planet, and any fixed star of Earth's sky. With such prominent appearances in Earth's sky, Venus has been a common and important object for humans, in both their cultures and astronomy."),
            new Planet(4, "Earth", "Earth (0.983–1.017 AU (147.1–152.1 million km; 91.4–94.5 million mi) from the Sun) is the largest and densest of the inner planets, the only one known to have current geological activity, and the only place in the universe where life is known to exist.[100] Its liquid hydrosphere is unique among the terrestrial planets, and it is the only planet where plate tectonics has been observed.[101] Earth's atmosphere is radically different from those of the other planets, having been altered by the presence of life to contain 21% free oxygen.[102][103] The planetary magnetosphere shields the surface from solar and cosmic radiation, limiting atmospheric stripping and maintaining habitability.[104] It has one natural satellite, the Moon, the only large satellite of a terrestrial planet in the Solar System."),
            new Planet(5, "Mars", "Mars (1.382–1.666 AU (206.7–249.2 million km; 128.5–154.9 million mi) from the Sun) is smaller than Earth and Venus (0.107 MEarth). It has an atmosphere of mostly carbon dioxide with a surface pressure of 6.1 millibars (0.088 psi; 0.18 inHg); roughly 0.6% of that of Earth but sufficient to support weather phenomena.[105] Its surface, peppered with volcanoes, such as Olympus Mons, and rift valleys, such as Valles Marineris, shows geological activity that may have persisted until as recently as 2 million years ago.[106] Its red color comes from iron oxide (rust) in its soil.[107] Mars has two tiny natural satellites (Deimos and Phobos) thought to be either captured asteroids,[108] or ejected debris from a massive impact early in Mars's history.[109]"),
            new Planet(6, "Jupiter", "Jupiter is the fifth planet from the Sun and the largest in the Solar System. It is a gas giant with a mass more than two and a half times that of all the other planets in the Solar System combined, and slightly less than one one-thousandth the mass of the Sun. Jupiter is the third brightest natural object in the Earth's night sky after the Moon and Venus, and it has been observed since prehistoric times. It was named after Jupiter, the chief deity of ancient Roman religion."),
            new Planet(7, "Saturn", "Saturn is the sixth planet from the Sun and the second-largest in the Solar System, after Jupiter. It is a gas giant with an average radius of about nine and a half times that of Earth.[25][26] It has only one-eighth the average density of Earth, but is over 95 times more massive.["),
            new Planet(8, "Uranus", "Uranus is the seventh planet from the Sun and is a gaseous cyan ice giant. Most of Uranus is made out of water, ammonia, and methane in a supercritical phase of matter, which in astronomy is called 'ice' or volatiles. The planet's atmosphere has a complex layered cloud structure and has the lowest minimum temperature of 49 K (−224 °C; −371 °F) out of all Solar System's planets. Uranus has a marked axial tilt of 97.8° with a retrograde rotation rate of 17 hours. This means that in an 84 Earth years orbital period around the Sun, its poles get around 42 years of continuous sunlight, followed by 42 years of continuous darkness."),
            new Planet(9, "Neptune", "Neptune is the eighth planet from the Sun and the farthest known planet in the Solar System. It is the fourth-largest planet in the Solar System by diameter, the third-most-massive planet, and the densest giant planet. It is 17 times the mass of Earth, and slightly more massive than its near-twin Uranus. Neptune is denser and physically smaller than Uranus because its greater mass causes more gravitational compression of its atmosphere. Being composed primarily of gases and liquids, it has no well-defined solid surface. The planet orbits the Sun once every 164.8 years at an average distance of 30.1 astronomical units (4.5 billion kilometres; 2.8 billion miles). It is named after the Roman god of the sea and has the astronomical symbol ♆, representing Neptune's trident.[d]")
        };
        public PlanetService()
        {
            this.AddRange(listPlanet);
        }

    }
}